### ISSUE TITLE
Should line 24 of src/__tests__/task-12_state.js say the component should only change with "new" state?

### ISSUE THREAD

**Issue by hamirmahal** [sveinpg/build-your-own-react#37]
[Line 24 of `src/__tests__/task-12_state.js`](https://github.com/sveinpg/build-your-own-react/blob/b7b55236c08395881c31cbb228c921ab9c3df9db/src/__tests__/task-12_state.js#L24) says `test('Check Component only changes given state', () => {`, but should it say `test('Check Component only changes given new state', () => {`, instead, since `Component` should only change when it receives new state?

**Comment by hamirmahal** [comment]
If so, I can submit a pull request for this.

**Comment by sveinpg** [comment]
Hi!

I can see why you find this confusing. The test actually checks if key-value pairs are preserved when another part of the state is updated

**Comment by hamirmahal** [comment]
Sorry I didn't respond to this earlier. I think aa426cc35ba7aafc3746c0678a7fb4ffb71904c1 fixes this by having [`src/__tests__/task-12_state.js`](https://github.com/sveinpg/build-your-own-react/commit/aa426cc35ba7aafc3746c0678a7fb4ffb71904c1#diff-9c3ec96b5854ffdf5d866e21a107f666c6e218f3d430a11b3f6b1cd68b4fcd1c) say `test('Check if key-value pairs are preserved when another part of the state is updatede', () => {`.

Thanks for updating it!
